export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT';
export const INCREMENT_AMOUNT_ASYNC_SAGA = 'INCREMENT_AMOUNT_ASYNC_SAGA';
