export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ASYNC_INCREMENT = 'ASYNC_INCREMENT';
export const INCREMENT_AMOUNT = 'INCREMENT_AMOUNT';
export const ASYNC_INCREMENT_AMOUNT = 'ASYNC_INCREMENT_AMOUNT';
